kind: Service
apiVersion: v1
metadata:
  name: device-management-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app:  devicemanagement-web-api
